/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TestSaasRouteImport } from './routes/test-saas'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FolderSlugRouteImport } from './routes/$folderSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FolderSlugIndexRouteImport } from './routes/$folderSlug/index'
import { Route as FeedFeedSlugRouteImport } from './routes/feed.$feedSlug'
import { Route as FolderSlugFeedSlugIndexRouteImport } from './routes/$folderSlug/$feedSlug/index'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSaasRoute = TestSaasRouteImport.update({
  id: '/test-saas',
  path: '/test-saas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSlugRoute = FolderSlugRouteImport.update({
  id: '/$folderSlug',
  path: '/$folderSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSlugIndexRoute = FolderSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FolderSlugRoute,
} as any)
const FeedFeedSlugRoute = FeedFeedSlugRouteImport.update({
  id: '/feed/$feedSlug',
  path: '/feed/$feedSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSlugFeedSlugIndexRoute = FolderSlugFeedSlugIndexRouteImport.update({
  id: '/$feedSlug/',
  path: '/$feedSlug/',
  getParentRoute: () => FolderSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$folderSlug': typeof FolderSlugRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/test-saas': typeof TestSaasRoute
  '/today': typeof TodayRoute
  '/feed/$feedSlug': typeof FeedFeedSlugRoute
  '/$folderSlug/': typeof FolderSlugIndexRoute
  '/$folderSlug/$feedSlug/': typeof FolderSlugFeedSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/test-saas': typeof TestSaasRoute
  '/today': typeof TodayRoute
  '/feed/$feedSlug': typeof FeedFeedSlugRoute
  '/$folderSlug': typeof FolderSlugIndexRoute
  '/$folderSlug/$feedSlug': typeof FolderSlugFeedSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$folderSlug': typeof FolderSlugRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/test-saas': typeof TestSaasRoute
  '/today': typeof TodayRoute
  '/feed/$feedSlug': typeof FeedFeedSlugRoute
  '/$folderSlug/': typeof FolderSlugIndexRoute
  '/$folderSlug/$feedSlug/': typeof FolderSlugFeedSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$folderSlug'
    | '/favorites'
    | '/test-saas'
    | '/today'
    | '/feed/$feedSlug'
    | '/$folderSlug/'
    | '/$folderSlug/$feedSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/test-saas'
    | '/today'
    | '/feed/$feedSlug'
    | '/$folderSlug'
    | '/$folderSlug/$feedSlug'
  id:
    | '__root__'
    | '/'
    | '/$folderSlug'
    | '/favorites'
    | '/test-saas'
    | '/today'
    | '/feed/$feedSlug'
    | '/$folderSlug/'
    | '/$folderSlug/$feedSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FolderSlugRoute: typeof FolderSlugRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  TestSaasRoute: typeof TestSaasRoute
  TodayRoute: typeof TodayRoute
  FeedFeedSlugRoute: typeof FeedFeedSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-saas': {
      id: '/test-saas'
      path: '/test-saas'
      fullPath: '/test-saas'
      preLoaderRoute: typeof TestSaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folderSlug': {
      id: '/$folderSlug'
      path: '/$folderSlug'
      fullPath: '/$folderSlug'
      preLoaderRoute: typeof FolderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folderSlug/': {
      id: '/$folderSlug/'
      path: '/'
      fullPath: '/$folderSlug/'
      preLoaderRoute: typeof FolderSlugIndexRouteImport
      parentRoute: typeof FolderSlugRoute
    }
    '/feed/$feedSlug': {
      id: '/feed/$feedSlug'
      path: '/feed/$feedSlug'
      fullPath: '/feed/$feedSlug'
      preLoaderRoute: typeof FeedFeedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folderSlug/$feedSlug/': {
      id: '/$folderSlug/$feedSlug/'
      path: '/$feedSlug'
      fullPath: '/$folderSlug/$feedSlug/'
      preLoaderRoute: typeof FolderSlugFeedSlugIndexRouteImport
      parentRoute: typeof FolderSlugRoute
    }
  }
}

interface FolderSlugRouteChildren {
  FolderSlugIndexRoute: typeof FolderSlugIndexRoute
  FolderSlugFeedSlugIndexRoute: typeof FolderSlugFeedSlugIndexRoute
}

const FolderSlugRouteChildren: FolderSlugRouteChildren = {
  FolderSlugIndexRoute: FolderSlugIndexRoute,
  FolderSlugFeedSlugIndexRoute: FolderSlugFeedSlugIndexRoute,
}

const FolderSlugRouteWithChildren = FolderSlugRoute._addFileChildren(
  FolderSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FolderSlugRoute: FolderSlugRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  TestSaasRoute: TestSaasRoute,
  TodayRoute: TodayRoute,
  FeedFeedSlugRoute: FeedFeedSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
